version: '3.7'
services:
  postgres:
    image: postgres:13
    container_name: postgres_db
    ports:
      - '5435:5432'
    environment:
      POSTGRES_DB: pet_db
      POSTGRES_USER: pet_user
      POSTGRES_PASSWORD: pet_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: